export const LOCAL_HOST = '/api';
export const GET_LAST_MESURE = LOCAL_HOST + "/mesures/last";
export const LOCAL_HOST_AUTOMATISATION = LOCAL_HOST +'/automatisation/';
export const GET_AUTOMATISATION = LOCAL_HOST_AUTOMATISATION + 'all';
export const UPDATE_AUTOMATISATION = LOCAL_HOST_AUTOMATISATION + 'update';
export const LOCAL_HOST_PIECE = LOCAL_HOST + '/piece/'
export const LOCAL_HOST_CAPTEUR_TESTPIECE = LOCAL_HOST + '/capteur_testpiece/'
export const GET_PIECES = LOCAL_HOST_PIECE + 'all'
export const GET_CAPTEURS_TESTPIECE = LOCAL_HOST_CAPTEUR_TESTPIECE + 'all'